var images = [
{"name":"Agria Manmade", src:"Agria_Manmade.jpg" },
{"name":"Agria Organic", src:"Agria_Organic.jpg" },
{"name":"Aiur City Cliff0", src:"Aiur_City_Cliff0.jpg" },
{"name":"Aiur Manmade", src:"Aiur_Manmade.jpg" },
{"name":"Aiur Organic", src:"Aiur_Organic.jpg" },
{"name":"Aiur Temple Cliff0", src:"Aiur_Temple_Cliff0.jpg" },
{"name":"Aiur Temple Cliff1", src:"Aiur_Temple_Cliff1.jpg" },
{"name":"Avernus Manmade", src:"Avernus_Manmade.jpg" },
{"name":"Avernus Organic", src:"Avernus_Organic.jpg" },
{"name":"Bel'Shir Manmade", src:"Bel'Shir_Manmade.jpg" },
{"name":"Bel'Shir Organic", src:"Bel'Shir_Organic.jpg" },
{"name":"Black Ops Lab Cliff0", src:"Black_Ops_Lab_Cliff0.jpg" },
{"name":"Braxis Alpha Manmade", src:"Braxis_Alpha_Manmade.jpg" },
{"name":"Braxis Alpha Organic", src:"Braxis_Alpha_Organic.jpg" },
{"name":"Castanar Manmade", src:"Castanar_Manmade.jpg" },
{"name":"Castanar Organic", src:"Castanar_Organic.jpg" },
{"name":"Char Marsh Organic 0", src:"Char_Marsh_Organic_0.jpg" },
{"name":"Char Marsh Organic 1", src:"Char_Marsh_Organic_1.jpg" },
{"name":"Char Organic", src:"Char_Organic.jpg" },
{"name":"Char2 0", src:"Char2_0.jpg" },
{"name":"Char2 1", src:"Char2_1.jpg" },
{"name":"Compound Facility Cliff0", src:"Compound_Facility_Cliff0.jpg" },
{"name":"Compound Facility Cliff1", src:"Compound_Facility_Cliff1.jpg" },
{"name":"Cybross0", src:"Cybross0.jpg" },
{"name":"Daelaam Ark Manmade", src:"Daelaam_Ark_Manmade.jpg" },
{"name":"Elsecaro Manmade", src:"Elsecaro_Manmade.jpg" },
{"name":"Elsecaro Organic", src:"Elsecaro_Organic.jpg" },
{"name":"Endion0", src:"Endion0.jpg" },
{"name":"Endion1", src:"Endion1.jpg" },
{"name":"EndionProtoss1", src:"EndionProtoss1.jpg" },
{"name":"Haven Organic", src:"Haven_Organic.jpg" },
{"name":"Immortal Forge Manmade", src:"Immortal_Forge_Manmade.jpg" },
{"name":"Immortal Forge Organic", src:"Immortal_Forge_Organic.jpg" },
{"name":"Jarban Minor Jungle Manmade", src:"Jarban_Minor_Jungle_Manmade.jpg" },
{"name":"Jarban Minor Jungle Organic", src:"Jarban_Minor_Jungle_Organic.jpg" },
{"name":"Kaldir Organic 0", src:"Kaldir_Organic_0.jpg" },
{"name":"Kaldir Organic 1", src:"Kaldir_Organic_1.jpg" },
{"name":"Korhal City Ex2", src:"Korhal_City_Ex2.jpg" },
{"name":"Korhal City Manmade", src:"Korhal_City_Manmade.jpg" },
{"name":"Korhal Manmade", src:"Korhal_Manmade.jpg" },
{"name":"Korhal Platform Ex2", src:"Korhal_Platform_Ex2.jpg" },
{"name":"Korhal Platform Manmade", src:"Korhal_Platform_Manmade.jpg" },
{"name":"Korhal Skyscraper", src:"Korhal_Skyscraper.jpg" },
{"name":"Korhal Wastes Manmade", src:"Korhal_Wastes_Manmade.jpg" },
{"name":"Korhal Wastes Organic", src:"Korhal_Wastes_Organic.jpg" },
{"name":"Mar Sara Manmade", src:"Mar_Sara_Manmade.jpg" },
{"name":"Mar Sara Organic", src:"Mar_Sara_Organic.jpg" },
{"name":"MarSaraEx20", src:"MarSaraEx20.jpg" },
{"name":"MarSaraEx21", src:"MarSaraEx21.jpg" },
{"name":"Meinhoff Manmade", src:"Meinhoff_Manmade.jpg" },
{"name":"Meinhoff Organic", src:"Meinhoff_Organic.jpg" },
{"name":"MoebiumLab0", src:"MoebiumLab0.jpg" },
{"name":"MoebiusLab1", src:"MoebiusLab1.jpg" },
{"name":"Monlyth Manmade", src:"Monlyth_Manmade.jpg" },
{"name":"Monlyth Organic", src:"Monlyth_Organic.jpg" },
{"name":"Moros Manmade", src:"Moros_Manmade.jpg" },
{"name":"New Folsom Manmade", src:"New_Folsom_Manmade.jpg" },
{"name":"New Folsom Organic", src:"New_Folsom_Organic.jpg" },
{"name":"Phaethon Organic", src:"Phaethon_Organic.jpg" },
{"name":"PortCityCliff1", src:"PortCityCliff1.jpg" },
{"name":"Port Zion Manmade", src:"Port_Zion_Manmade.jpg" },
{"name":"Port Zion Organic", src:"Port_Zion_Organic.jpg" },
{"name":"Protoss Base Manmade", src:"Protoss_Base_Manmade.jpg" },
{"name":"Protoss Base Organic", src:"Protoss_Base_Organic.jpg" },
{"name":"Redstone Manmade", src:"Redstone_Manmade.jpg" },
{"name":"Redstone Organic", src:"Redstone_Organic.jpg" },
{"name":"ShadowCorpsPlatform0", src:"ShadowCorpsPlatform0.jpg" },
{"name":"ShadowCorpsPlatform1", src:"ShadowCorpsPlatform1.jpg" },
{"name":"Shakuras Manmade", src:"Shakuras_Manmade.jpg" },
{"name":"Shakuras Organic", src:"Shakuras_Organic.jpg" },
{"name":"ShakurasTemple0", src:"ShakurasTemple0.jpg" },
{"name":"ShakurasTemple1", src:"ShakurasTemple1.jpg" },
{"name":"Skygeirr Lab Manmade", src:"Skygeirr_Lab_Manmade.jpg" },
{"name":"Skygeirr Lab Natural", src:"Skygeirr_Lab_Natural.jpg" },
{"name":"Skygeirr Platform Manmade 0", src:"Skygeirr_Platform_Manmade_0.jpg" },
{"name":"Skygeirr Platform Manmade 1", src:"Skygeirr_Platform_Manmade_1.jpg" },
{"name":"Slayn0", src:"Slayn0.jpg" },
{"name":"Slayn1", src:"Slayn1.jpg" },
{"name":"SnowRefineryCliff1", src:"SnowRefineryCliff1.jpg" },
{"name":"TarsonisCityCliff0", src:"TarsonisCityCliff0.jpg" },
{"name":"TarsonisCityCliff1", src:"TarsonisCityCliff1.jpg" },
{"name":"Tarsonis Manmade", src:"Tarsonis_Manmade.jpg" },
{"name":"Tarsonis Organic", src:"Tarsonis_Organic.jpg" },
{"name":"TheVoid0", src:"TheVoid0.jpg" },
{"name":"TheVoid1", src:"TheVoid1.jpg" },
{"name":"Typhon Manmade", src:"Typhon_Manmade.jpg" },
{"name":"Typhon Organic", src:"Typhon_Organic.jpg" },
{"name":"Tyrador Manmade", src:"Tyrador_Manmade.jpg" },
{"name":"Ulaan Manmade", src:"Ulaan_Manmade.jpg" },
{"name":"Ulaan Organic", src:"Ulaan_Organic.jpg" },
{"name":"Ulna Inner1", src:"Ulna_Inner1.jpg" },
{"name":"Ulnar Inner0", src:"Ulnar_Inner0.jpg" },
{"name":"Ulnar Manmade", src:"Ulnar_Manmade.jpg" },
{"name":"Ulnar Organic", src:"Ulnar_Organic.jpg" },
{"name":"Ulnar Outer0", src:"Ulnar_Outer0.jpg" },
{"name":"Ulnar Outer1", src:"Ulnar_Outer1.jpg" },
{"name":"UlnarPortal0", src:"UlnarPortal0.jpg" },
{"name":"UlnarPortal1", src:"UlnarPortal1.jpg" },
{"name":"Umoja Lab Manmade", src:"Umoja_Lab_Manmade.jpg" },
{"name":"Umoja Lab Organic", src:"Umoja_Lab_Organic.jpg" },
{"name":"Valhalla Manmade", src:"Valhalla_Manmade.jpg" },
{"name":"Valhalla Organic", src:"Valhalla_Organic.jpg" },
{"name":"Xil Manmade", src:"Xil_Manmade.jpg" },
{"name":"Xil Organic", src:"Xil_Organic.jpg" },
{"name":"Zerus Organic 0", src:"Zerus_Organic_0.jpg" },
{"name":"Zerus Organic 1", src:"Zerus_Organic_1.jpg" },
{"name":"Zhakul'Das Manmade", src:"Zhakul'Das_Manmade.jpg" },
{"name":"Zhakul'Das Organic", src:"Zhakul'Das_Organic.jpg" }

]

jQuery.each( images, function( i, value ) {
	$( "#gallery" ).append( '<figure class="reference_image">\n<a href="cliffs/'+value["src"]+'" rel="gallery" title="'+value["name"]+'">\n<img src="loading.png" data-src="cliffs/thumbs/'+value["src"]+'">\n<figcaption>\n'+value["name"]+'\n</figcaption>\n</a>\n</figure>' );
});
$("figure img").unveil();